apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mern
resources:
  - namespace.yaml
  - mongo-pvc.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - app-deployment.yaml
  - app-service.yaml
